apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skybook-ingress
  namespace: skybook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - skybook.example.com
      secretName: skybook-tls
  rules:
    - host: skybook.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: skybook-backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skybook-frontend-svc
                port:
                  number: 3000
